### ISSUE TITLE
I have come once again

### ISSUE THREAD

**Issue by Hunter-171** [PiggyAwesome/This-Repository-Has-60-Stars#22]
I was scrolling through my for your and i rediscovered this repository. I was greatly saddened when the name was not matching with the stars.
![image](https://user-images.githubusercontent.com/99055264/223167870-524ba72b-00ba-47f0-a01a-0f76bb004f0c.png)
I will fix for this error of +1 by unstarring this repo.

**Comment by PiggyAwesome** [comment]
Thank you for restoring the balance yet again.
